### PR TITLE
Asa branch

### PR DESCRIPTION
**Pull request by emresaglam**
Hi Joe,
As promised, I created a parser for the ASA logs. The magic happens between lines 47-60. If the src/dst logs are not in ipv4 format, it will reject them and return 2.

TODO for this would be, if we have a domain name instead of an IP we shout do a host to ip lookup. Cisco sometimes logs with the IP sometimes with the domain or object name. Because Cisco....

Cheers
Emre

### CODE REVIEW

**Comment by emresaglam** [comment]
Oh I also didn't have a chance to test the entire installation, but since I used the palo alto import script, this should work. If it doesn't please let me know.

**Comment by JoePelz** [comment]
It looks good! 
One question: why did you comment out the dbaccess module? 
If line 116 were ever to run then dbaccess would be not defined

**Comment by emresaglam** [comment]
Totally by mistake. :(

**Comment by JoePelz** [comment]
If you could just uncomment that line again, I'll happily merge the pull request

**Pull request merged**
